name: PerformanceDebugger
main: org.cat73.performancedebugger.PerformanceDebugger
author: Cat73
website: https://github.com/Cat7373/PerformanceDebugger
version: 1.0.0
commands:
  performancedebugger:
    usage: /<command> help
    aliases: [pd]
    permission: performancedebugger.use
    permission-message: You don't have <permission>
permissions:
  performancedebugger.use:
    default: op
  performancedebugger.help:
    default: op
  performancedebugger.dumpchunks:
    default: op
  performancedebugger.playersinfo:
    default: op
  performancedebugger.top:
    default: op
  performancedebugger.tpchunk:
    default: op
  performancedebugger.tps:
    default: op
